### PR TITLE
Peter Hanraets Make openmsx.exe a GUI application (but still allow --help to output

### PR DESCRIPTION
**Pull request by sdsnatcher73**

### CODE REVIEW

**Comment by sdsnatcher73** [comment]
Implements #1325 for mingw builds, if accepted a change shoiuld be made to the visual studio build.

**Comment by MBilderbeek** [comment]
Are you also going to submit a patch for the VS build? (Which is the main/mainstream build for Windows...)

**Comment by sdsnatcher73** [comment]
I am trying to build the Visual Studio solution but am running into issue. Started with VS Community 2019 that had issues with the zlib build. So I thought maybe I need 2017 but that seems to old as it returns error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. Still figuring this out...

**Comment by sdsnatcher73** [comment]
Okay it was just a huge list of warnings...

**Comment by sdsnatcher73** [comment]
msvc build also updated

**Comment by sdsnatcher73** [comment]
I changed the Subsystem from Console to Windows from within the IDE (I tried first manually with VSCode but it said the root structure was not valid or something like that). The change in the IDE also did the changes to the filters file.

**Comment by sdsnatcher73** [comment]
I don't understand why there are so many duplicates in that file, I guess optimisation is not a priority on MS's shortlist...

**Review by MBilderbeek — APPROVED** [review]
OK, let's just see. We can always (partially) revert things if they don't work out as we expected.

**Comment by sdsnatcher73** [comment]
Yeah makes sense. if anything pops up you'll know where to find me ;)

**Pull request merged**
