### PR TITLE
Identified some pieces of software that had their protections removed.

### PR DESCRIPTION
**Pull request by wilbertpol**

### CODE REVIEW

**Comment by Vampier** [comment]
Oh no… do you have only the sha1 values for me and the comment you added? Here is the problem - this database is the result of a SQL database that generates this XML file. So I would have to update the source for these changes to be permanent. 

I appreciate all the work you put in here and I might just add a flag to the romdb to indicate that these ROMs had protection removed.

**Comment by wilbertpol** [comment]
> Oh no… do you have only the sha1 values for me and the comment you added? Here is the problem - this database is the result of a SQL database that generates this XML file. So I would have to update the source for these changes to be permanent.
> 
> I appreciate all the work you put in here and I might just add a flag to the romdb to indicate that these ROMs had protection removed.

Of course. There were also a few where the version or different copyright year was found:
ee7dbd36a2b0bbae11c68ac4de75077f283bed05, [a1], v1.0
f86a7945b34c97cc58d5ee27964968870bfcef93, v1.04
9b58c70b976ca1d841185de862e7d663ec9db56b, v1.03
0f214ea9e8d673ee0c66cb6615032e57920d588b, [a], 1984

f3815211c6183b4f9c26b9e7d0a12c3b3870bdda, [cr protection]
2185be579cb51729f66bf02bdf3a7b6a3cbd7b40, [cr protection]
47ea8d512d9fec15df8770f3b5017aea9bbba9fd, [cr protection]
308c73fc04c3b390b72ea8d4980c94c74ba38a5c, [a][cr protection]
5e28fa0cd90bcfb7995acb025a22f6f556ccac08, [cr protection]
d1a7cbaff354b59003f0e297723b912cb6ad0b36, [cr protection]
14393568469c74bd6f8be7770149db19f0553ab6, [cr protection]
3b13e164130cab9b36c1a95e06f8d9fd707fc97f, [RC-718][cr protection]
ec76d4d9b61bdbde9a4b5be082dbdae96321a591, [cr protection]
6842fb21abb2531c17fe0687d77e012348d3dc2c, [RC-733][cr protection]
43dc3911b9a336bb7b17bdbe6e48464e01f2c425, [a2][RC-727][cr protection]
8c9a9a9afe13a58e4cfb72489af2d6b080dffaf6, [a4][RC-727][cr protection]
a4383f789482a9e868a9f136aa722129673c2a81, [RC-727][cr protection]
da8249452da86c0ba44f0ae279ccff82a1ddd756, [cr protection]
1d6a355a9ce84c78e3bafc27a4f1151e240f68f0, [RC-739][cr protection]
9bdfe44a7a0d5151346ff14ece3216b5108cc775, [RC-724][cr protection]
9e190cf3ca52d85fd34eb5df2c0dd8490448b9a2, [cr protection]
5e349166fce12d45f3ce3f69ecd6b2a70ef4d68b, [RC-736][cr protection]
5c7971aa8688ffc429a3e315dd3d45c38f72ddeb, [RC-723][cr protection]
6c68f7be1eb46cca6dcdbb9192cbff9d59604357, [cr protection]
5e1a50affe1fa973f69e423a8827751b93fc53ee, [RC-731][cr protection]
eaa6b787784bae1c7f648b57daa1c88cf2b1b095, [cr protection]
10698ea6b0423f2e858a4c28c10f39646ca5495f, [cr protection]
a0ed2c50e55241d23bb5d12cb6528a2a0c3bc156, [cr protection]
79c1bf77c08b733ae04e069deaf25fd24b28beb7, [RC-732][cr protection]
a3d1212eb4c58958f063aa8577ddfa07903b28b3, [a][cr protection]
f1d68b477f3f54c0b6080985954208b0d95c5973, [a][cr protection]
14e7ef125cc902001995bbd8acca0eae2f213dc1, [cr protection]
ddc458bb3c70e0708841e516d9b89220c0e098a1, [cr protection]
0a9c576eabaf2651ddca35bf17f96e509d6c6ba0, [cr protection]
d621e2a2f0f924a17673f5d47f2182095074acf4, [cr protection]
cf8e40315f34e30e1be4776bbebc08c0a8403523, [RC-729][cr protection]
2fa9c0f016efc2d1752a272c632393f5063ea06c, [cr protection]
2e16a588246743c9b901afdbf1ba094a0b1c8b5d, [cr protection]
ac381dfb4d0b52dedb18a8df7a4651ed2978d12f, [a][cr protection]
fe1d02284b0b051308e3c796e8e9eee2f86521b8, [a2][cr protection]
cd466c04209a8815a95d3723653e263a868de9e0, [cr protection]
e9398aceb9f8a648e4bcebe02e5d7b14a3744c7d, [cr protection]
250d0d6e646eae4817802c49e367ad8c1c35a462, [cr protection]
b7b4d5c83d8c336dbfe32833bba974cea7f0cb8d, [RC-734][cr protection]
049e7dccd3977049b5f68aad7754105b014ba771, [a2][cr protection]
6420473ec647e4d750bc2247020b6722435b5211, [cr protection]
751d722a4f36a03e88ac62118ae8d880e40c1c84, [cr protection]
adb3977309d373ad1dc995ae7d2f8280f1673d66, [cr protection]
8b828d33dcdfd324df1827ef79f5ca9635968c6e, [RC-740][cr protection]
5017abeca8fbed43ff2fd1a936843acdc7192dcc, [cr protection]

I found these while working on MAME and thought I'd pass these findings on.

**Comment by Vampier** [comment]
Thanks :) I seriously was already thinking about writing a parser to get the diffs. But this is easier. I will add a cracked flag to the database as I am rebuilding the interface. The old web interface to maintain the romdb had some issues.  https://romdb.vampier.net/Thanks for all the work.VampierSent from my iPhoneOn Mar 17, 2023, at 16:46, wilbertpol ***@***.***> wrote:﻿

Oh no… do you have only the sha1 values for me and the comment you added? Here is the problem - this database is the result of a SQL database that generates this XML file. So I would have to update the source for these changes to be permanent.
I appreciate all the work you put in here and I might just add a flag to the romdb to indicate that these ROMs had protection removed.

Of course. There were also a few where the version or different copyright year was found:
ee7dbd36a2b0bbae11c68ac4de75077f283bed05, [a1], v1.0
f86a7945b34c97cc58d5ee27964968870bfcef93, v1.04
9b58c70b976ca1d841185de862e7d663ec9db56b, v1.03
0f214ea9e8d673ee0c66cb6615032e57920d588b, [a], 1984
f3815211c6183b4f9c26b9e7d0a12c3b3870bdda, [cr protection]
2185be579cb51729f66bf02bdf3a7b6a3cbd7b40, [cr protection]
47ea8d512d9fec15df8770f3b5017aea9bbba9fd, [cr protection]
308c73fc04c3b390b72ea8d4980c94c74ba38a5c, [a][cr protection]
5e28fa0cd90bcfb7995acb025a22f6f556ccac08, [cr protection]
d1a7cbaff354b59003f0e297723b912cb6ad0b36, [cr protection]
14393568469c74bd6f8be7770149db19f0553ab6, [cr protection]
3b13e164130cab9b36c1a95e06f8d9fd707fc97f, [RC-718][cr protection]
ec76d4d9b61bdbde9a4b5be082dbdae96321a591, [cr protection]
6842fb21abb2531c17fe0687d77e012348d3dc2c, [RC-733][cr protection]
43dc3911b9a336bb7b17bdbe6e48464e01f2c425, [a2][RC-727][cr protection]
8c9a9a9afe13a58e4cfb72489af2d6b080dffaf6, [a4][RC-727][cr protection]
a4383f789482a9e868a9f136aa722129673c2a81, [RC-727][cr protection]
da8249452da86c0ba44f0ae279ccff82a1ddd756, [cr protection]
1d6a355a9ce84c78e3bafc27a4f1151e240f68f0, [RC-739][cr protection]
9bdfe44a7a0d5151346ff14ece3216b5108cc775, [RC-724][cr protection]
9e190cf3ca52d85fd34eb5df2c0dd8490448b9a2, [cr protection]
5e349166fce12d45f3ce3f69ecd6b2a70ef4d68b, [RC-736][cr protection]
5c7971aa8688ffc429a3e315dd3d45c38f72ddeb, [RC-723][cr protection]
6c68f7be1eb46cca6dcdbb9192cbff9d59604357, [cr protection]
5e1a50affe1fa973f69e423a8827751b93fc53ee, [RC-731][cr protection]
eaa6b787784bae1c7f648b57daa1c88cf2b1b095, [cr protection]
10698ea6b0423f2e858a4c28c10f39646ca5495f, [cr protection]
a0ed2c50e55241d23bb5d12cb6528a2a0c3bc156, [cr protection]
79c1bf77c08b733ae04e069deaf25fd24b28beb7, [RC-732][cr protection]
a3d1212eb4c58958f063aa8577ddfa07903b28b3, [a][cr protection]
f1d68b477f3f54c0b6080985954208b0d95c5973, [a][cr protection]
14e7ef125cc902001995bbd8acca0eae2f213dc1, [cr protection]
ddc458bb3c70e0708841e516d9b89220c0e098a1, [cr protection]
0a9c576eabaf2651ddca35bf17f96e509d6c6ba0, [cr protection]
d621e2a2f0f924a17673f5d47f2182095074acf4, [cr protection]
cf8e40315f34e30e1be4776bbebc08c0a8403523, [RC-729][cr protection]
2fa9c0f016efc2d1752a272c632393f5063ea06c, [cr protection]
2e16a588246743c9b901afdbf1ba094a0b1c8b5d, [cr protection]
ac381dfb4d0b52dedb18a8df7a4651ed2978d12f, [a][cr protection]
fe1d02284b0b051308e3c796e8e9eee2f86521b8, [a2][cr protection]
cd466c04209a8815a95d3723653e263a868de9e0, [cr protection]
e9398aceb9f8a648e4bcebe02e5d7b14a3744c7d, [cr protection]
250d0d6e646eae4817802c49e367ad8c1c35a462, [cr protection]
b7b4d5c83d8c336dbfe32833bba974cea7f0cb8d, [RC-734][cr protection]
049e7dccd3977049b5f68aad7754105b014ba771, [a2][cr protection]
6420473ec647e4d750bc2247020b6722435b5211, [cr protection]
751d722a4f36a03e88ac62118ae8d880e40c1c84, [cr protection]
adb3977309d373ad1dc995ae7d2f8280f1673d66, [cr protection]
8b828d33dcdfd324df1827ef79f5ca9635968c6e, [RC-740][cr protection]
5017abeca8fbed43ff2fd1a936843acdc7192dcc, [cr protection]

**Comment by Vampier** [comment]
I merged your changes with the database.

https://github.com/openMSX/openMSX/commit/b14ad788b02e3223fd95c3206dc6124783a52d3a

**Comment by Vampier** [comment]
@wilbertpol thanks for the information - please contact me directly when you have changes. I'll make sure to integrate them into the romdb.

**Comment by wilbertpol** [comment]
Ok, I will. Glad I could help.

**Pull request closed without merging**
